// Auto-generated by scripts/extract-claude-models.sh
// Run: bash scripts/extract-claude-models.sh
// Source: model catalog embedded in 2.1.263 (Claude Code)

export type ClaudeCatalogEffort = "low" | "medium" | "high" | "xhigh" | "max";

export interface ClaudeCatalogModel {
  label: string;
  value: string;
  knowledgeCutoff: string;
  /** Empty for models that predate `--effort`. */
  supportedEfforts: ClaudeCatalogEffort[];
}

export interface ClaudeModelAlias {
  label: string;
  value: string;
}

/** Newest first within each family. */
export const claudeCatalogModels: ClaudeCatalogModel[] = [
  {
    label: "Opus 5",
    value: "claude-opus-5",
    knowledgeCutoff: "May 2026",
    supportedEfforts: ["low", "medium", "high", "xhigh", "max"],
  },
  {
    label: "Opus 4.8",
    value: "claude-opus-4-8",
    knowledgeCutoff: "January 2026",
    supportedEfforts: ["low", "medium", "high", "xhigh", "max"],
  },
  {
    label: "Opus 4.7",
    value: "claude-opus-4-7",
    knowledgeCutoff: "January 2026",
    supportedEfforts: ["low", "medium", "high", "xhigh", "max"],
  },
  {
    label: "Opus 4.6",
    value: "claude-opus-4-6",
    knowledgeCutoff: "May 2025",
    supportedEfforts: ["low", "medium", "high", "max"],
  },
  {
    label: "Opus 4.5",
    value: "claude-opus-4-5",
    knowledgeCutoff: "May 2025",
    supportedEfforts: [],
  },
  {
    label: "Opus 4.1",
    value: "claude-opus-4-1",
    knowledgeCutoff: "January 2025",
    supportedEfforts: [],
  },
  {
    label: "Opus 4",
    value: "claude-opus-4-0",
    knowledgeCutoff: "January 2025",
    supportedEfforts: [],
  },
  {
    label: "Sonnet 5",
    value: "claude-sonnet-5",
    knowledgeCutoff: "January 2026",
    supportedEfforts: ["low", "medium", "high", "xhigh", "max"],
  },
  {
    label: "Sonnet 4.6",
    value: "claude-sonnet-4-6",
    knowledgeCutoff: "August 2025",
    supportedEfforts: ["low", "medium", "high", "max"],
  },
  {
    label: "Sonnet 4.5",
    value: "claude-sonnet-4-5",
    knowledgeCutoff: "January 2025",
    supportedEfforts: [],
  },
  {
    label: "Sonnet 4",
    value: "claude-sonnet-4-0",
    knowledgeCutoff: "January 2025",
    supportedEfforts: [],
  },
  {
    label: "Haiku 4.5",
    value: "claude-haiku-4-5",
    knowledgeCutoff: "February 2025",
    supportedEfforts: [],
  },
  {
    label: "Fable 5.1",
    value: "claude-fable-5-1",
    knowledgeCutoff: "June 2026",
    supportedEfforts: ["low", "medium", "high", "xhigh", "max"],
  },
  {
    label: "Fable 5",
    value: "claude-fable-5",
    knowledgeCutoff: "January 2026",
    supportedEfforts: ["low", "medium", "high", "xhigh", "max"],
  },
];

export const claudeModelAliases: ClaudeModelAlias[] = [
  {
    label: "Opus (latest)",
    value: "opus",
  },
  {
    label: "Sonnet (latest)",
    value: "sonnet",
  },
  {
    label: "Haiku (latest)",
    value: "haiku",
  },
  {
    label: "Fable (latest)",
    value: "fable",
  },
  {
    label: "Opus (latest, 1M context)",
    value: "opus[1m]",
  },
  {
    label: "Sonnet (latest, 1M context)",
    value: "sonnet[1m]",
  },
  {
    label: "Fable (latest, 1M context)",
    value: "fable[1m]",
  },
  {
    label: "Best available",
    value: "best",
  },
  {
    label: "Opus for planning, Sonnet for execution",
    value: "opusplan",
  },
];
